version: '3.8'
services:
  backend:
    build: ./micro-task-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./micro-task-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped