pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/your-repo.git'
      }
    }
    stage('Build Frontend') {
      steps {
        dir('micro-task-client') {
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
    stage('Docker Build') {
      steps {
        dir('micro-task-client') {
          sh 'docker build -t frontend-app .'
        }
      }
    }
  }
}